name: pyPhoPlaceCellAnalysis
channels:
  # - defaults
  - conda-forge
  # - pytorch
  # - fastai
dependencies:
  - python>=3.9
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - pandas-flavor
  - numba
  - tqdm
  - click
  - ipython
  # VISUALIZATION
  - matplotlib
  - ipympl  # interactive matplotlib plots
  - seaborn
  - pyqtgraph
  - qtmodern
  - pyvista
  - pyvistaqt
  - param
  - panel
  - pillow
  - opencv
  - openmp
  # - altair
  # - yellowbrick
  # Personal Libraries
  # - pyPhoCoreHelpers
  # ML, STATS & DEEP LEARNING
  # - statsmodels
  # - scikit-learn
  # - sktime
  # - tslearn
  # - xgboost
  # - catboost
  # - lightgbm
  # - pytorch
  # - fastai  # activate fastai channel above!
  # - tensorflow
  # - keras
  # - spacy
  # OTHER TOOLS
  # - optuna
  # - dask
  # - snakeviz
  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - pip:
     - -e .  # install git checkout of pyPhoPlaceCellAnalysis in editable mode
    #  - pyPhoCoreHelpers
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
    #  - pyqt6
    #  - pyqt6-tools
     - pyqt5
     - pyqt5-tools
     - indexed # for IndexedOrderedDict from the indexed package
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib


