"""
This type stub file was generated by pyright.
"""

def interlieve_points(start_points, end_points): # -> NDArray[Any]:
    ...

def lines_from_points(points): # -> PolyData:
    """Given an array of points, make a line set"""
    ...

