# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\pyPhoPlaceCellAnalysis\src\pyphoplacecellanalysis\GUI\Qt\PlaybackControls\Spike3DRasterBottomPlaybackControlBarBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RootWidget(object):
    def setupUi(self, RootWidget):
        RootWidget.setObjectName("RootWidget")
        RootWidget.resize(1663, 70)
        RootWidget.setStyleSheet("background-color: rgb(71, 58, 46);\n"
"border-color: rgb(207, 207, 207);\n"
"background-color: rgba(71, 65, 60, 180);\n"
"color: rgb(244, 244, 244);\n"
"border : 1px solid black;\n"
"border-color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(255, 0, 0);\n"
"selection-background-color: rgb(75, 83, 65);\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(RootWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_media_control = QtWidgets.QFrame(RootWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_media_control.sizePolicy().hasHeightForWidth())
        self.frame_media_control.setSizePolicy(sizePolicy)
        self.frame_media_control.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_media_control.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_media_control.setStyleSheet("background:transparent;")
        self.frame_media_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_media_control.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_media_control.setLineWidth(1)
        self.frame_media_control.setObjectName("frame_media_control")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_media_control)
        self.gridLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnSkipLeft = QtWidgets.QToolButton(self.frame_media_control)
        self.btnSkipLeft.setObjectName("btnSkipLeft")
        self.gridLayout_2.addWidget(self.btnSkipLeft, 1, 16, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.slider_progress = HighlightedJumpSlider(self.frame_media_control)
        self.slider_progress.setEnabled(False)
        self.slider_progress.setMaximum(9999)
        self.slider_progress.setPageStep(1)
        self.slider_progress.setOrientation(QtCore.Qt.Horizontal)
        self.slider_progress.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_progress.setObjectName("slider_progress")
        self.gridLayout_2.addWidget(self.slider_progress, 0, 0, 1, 23)
        self.toolButton_SpeedBurstEnabled = QtWidgets.QToolButton(self.frame_media_control)
        self.toolButton_SpeedBurstEnabled.setEnabled(False)
        self.toolButton_SpeedBurstEnabled.setCheckable(True)
        self.toolButton_SpeedBurstEnabled.setChecked(True)
        self.toolButton_SpeedBurstEnabled.setObjectName("toolButton_SpeedBurstEnabled")
        self.gridLayout_2.addWidget(self.toolButton_SpeedBurstEnabled, 1, 5, 1, 1)
        self.btnLeft = QtWidgets.QToolButton(self.frame_media_control)
        self.btnLeft.setArrowType(QtCore.Qt.LeftArrow)
        self.btnLeft.setObjectName("btnLeft")
        self.gridLayout_2.addWidget(self.btnLeft, 1, 17, 1, 1)
        self.btnRight = QtWidgets.QToolButton(self.frame_media_control)
        self.btnRight.setArrowType(QtCore.Qt.RightArrow)
        self.btnRight.setObjectName("btnRight")
        self.gridLayout_2.addWidget(self.btnRight, 1, 19, 1, 1)
        self.button_play_pause = ToggleButton(self.frame_media_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_play_pause.sizePolicy().hasHeightForWidth())
        self.button_play_pause.setSizePolicy(sizePolicy)
        self.button_play_pause.setToolTip("Toggle Play/Pause")
        self.button_play_pause.setCheckable(False)
        self.button_play_pause.setObjectName("button_play_pause")
        self.gridLayout_2.addWidget(self.button_play_pause, 1, 0, 1, 1)
        self.button_speed_up = QtWidgets.QPushButton(self.frame_media_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_speed_up.sizePolicy().hasHeightForWidth())
        self.button_speed_up.setSizePolicy(sizePolicy)
        self.button_speed_up.setToolTip("Speed up the playback")
        self.button_speed_up.setObjectName("button_speed_up")
        self.gridLayout_2.addWidget(self.button_speed_up, 1, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 15, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_media_control)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnJumpToPrevious = QtWidgets.QToolButton(self.frame)
        self.btnJumpToPrevious.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.00564972, y1:0.284, x2:0, y2:1, stop:0.0918367 rgba(255, 233, 191, 255), stop:0.136364 rgba(47, 43, 39, 255), stop:0.408163 rgba(84, 77, 70, 255));")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/Icon/JumpToPrev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnJumpToPrevious.setIcon(icon)
        self.btnJumpToPrevious.setIconSize(QtCore.QSize(32, 32))
        self.btnJumpToPrevious.setObjectName("btnJumpToPrevious")
        self.horizontalLayout.addWidget(self.btnJumpToPrevious)
        self.btnJumpToUnused = QtWidgets.QToolButton(self.frame)
        self.btnJumpToUnused.setEnabled(False)
        self.btnJumpToUnused.setObjectName("btnJumpToUnused")
        self.horizontalLayout.addWidget(self.btnJumpToUnused)
        self.comboActiveJumpTargetSeries = QtWidgets.QComboBox(self.frame)
        self.comboActiveJumpTargetSeries.setMinimumSize(QtCore.QSize(80, 0))
        self.comboActiveJumpTargetSeries.setBaseSize(QtCore.QSize(100, 0))
        self.comboActiveJumpTargetSeries.setCurrentText("")
        self.comboActiveJumpTargetSeries.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboActiveJumpTargetSeries.setObjectName("comboActiveJumpTargetSeries")
        self.horizontalLayout.addWidget(self.comboActiveJumpTargetSeries)
        self.btnJumpToNext = QtWidgets.QToolButton(self.frame)
        self.btnJumpToNext.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.00564972, y1:0.284, x2:0, y2:1, stop:0.0918367 rgba(255, 233, 191, 255), stop:0.136364 rgba(47, 43, 39, 255), stop:0.408163 rgba(84, 77, 70, 255));")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/Icon/JumpToNext.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnJumpToNext.setIcon(icon1)
        self.btnJumpToNext.setIconSize(QtCore.QSize(32, 32))
        self.btnJumpToNext.setObjectName("btnJumpToNext")
        self.horizontalLayout.addWidget(self.btnJumpToNext)
        self.gridLayout_2.addWidget(self.frame, 1, 12, 1, 1, QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 13, 1, 1)
        self.button_slow_down = QtWidgets.QPushButton(self.frame_media_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_slow_down.sizePolicy().hasHeightForWidth())
        self.button_slow_down.setSizePolicy(sizePolicy)
        self.button_slow_down.setToolTip("Slow down the playback")
        self.button_slow_down.setObjectName("button_slow_down")
        self.gridLayout_2.addWidget(self.button_slow_down, 1, 3, 1, 1)
        self.btnHelp = QtWidgets.QPushButton(self.frame_media_control)
        self.btnHelp.setObjectName("btnHelp")
        self.gridLayout_2.addWidget(self.btnHelp, 1, 22, 1, 1)
        self.button_reverse = QtWidgets.QPushButton(self.frame_media_control)
        self.button_reverse.setMinimumSize(QtCore.QSize(30, 25))
        self.button_reverse.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-color: rgb(85, 170, 255);\n"
"selection-background-color: rgb(85, 170, 255);\n"
"background-color: rgb(65, 60, 54);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.button_reverse.setCheckable(True)
        self.button_reverse.setObjectName("button_reverse")
        self.gridLayout_2.addWidget(self.button_reverse, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 8, 1, 1)
        self.doubleSpinBoxPlaybackSpeed = QtWidgets.QDoubleSpinBox(self.frame_media_control)
        self.doubleSpinBoxPlaybackSpeed.setToolTip("Playback Speed Multiplier")
        self.doubleSpinBoxPlaybackSpeed.setWhatsThis("Playback Speed Multiplier")
        self.doubleSpinBoxPlaybackSpeed.setStyleSheet("QDoubleSpinBox {\n"
"    background: rgb(62, 57, 52);\n"
"    border : 1px solid black;\n"
"};\n"
"QDoubleSpinBox::hover {\n"
"    background: rgb(75, 83, 65);\n"
"    border : 1px solid black;\n"
"};\n"
"QDoubleSpinBox::up-arrow {\n"
"    background: rgb(62, 57, 52);\n"
"    color: rgb(255, 255, 255);\n"
"    border :1px solid black;\n"
"};\n"
"QDoubleSpinBox::down-arrow {\n"
"    background: rgb(62, 57, 52);\n"
"    color: rgb(255, 255, 255);\n"
"    border : 1px solid black;\n"
"};")
        self.doubleSpinBoxPlaybackSpeed.setMinimum(0.2)
        self.doubleSpinBoxPlaybackSpeed.setMaximum(6.0)
        self.doubleSpinBoxPlaybackSpeed.setProperty("value", 1.0)
        self.doubleSpinBoxPlaybackSpeed.setObjectName("doubleSpinBoxPlaybackSpeed")
        self.gridLayout_2.addWidget(self.doubleSpinBoxPlaybackSpeed, 1, 4, 1, 1)
        self.button_full_screen = QtWidgets.QPushButton(self.frame_media_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_full_screen.sizePolicy().hasHeightForWidth())
        self.button_full_screen.setSizePolicy(sizePolicy)
        self.button_full_screen.setObjectName("button_full_screen")
        self.gridLayout_2.addWidget(self.button_full_screen, 1, 14, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 21, 1, 1)
        self.spinBoxFrameJumpMultiplier = QtWidgets.QSpinBox(self.frame_media_control)
        self.spinBoxFrameJumpMultiplier.setToolTip("Frame Jump Multiplier")
        self.spinBoxFrameJumpMultiplier.setWhatsThis("Frame Jump Multiplier")
        self.spinBoxFrameJumpMultiplier.setStyleSheet("QSpinBox {\n"
"    background: rgb(62, 57, 52);\n"
"    border : 1px solid black;\n"
"};\n"
"QSpinBox::hover {\n"
"    background: rgb(75, 83, 65);\n"
"    border : 1px solid black;\n"
"};\n"
"")
        self.spinBoxFrameJumpMultiplier.setMinimum(1)
        self.spinBoxFrameJumpMultiplier.setMaximum(1000)
        self.spinBoxFrameJumpMultiplier.setObjectName("spinBoxFrameJumpMultiplier")
        self.gridLayout_2.addWidget(self.spinBoxFrameJumpMultiplier, 1, 18, 1, 1)
        self.button_mark_end = QtWidgets.QPushButton(self.frame_media_control)
        self.button_mark_end.setObjectName("button_mark_end")
        self.gridLayout_2.addWidget(self.button_mark_end, 1, 10, 1, 1)
        self.button_mark_start = QtWidgets.QPushButton(self.frame_media_control)
        self.button_mark_start.setObjectName("button_mark_start")
        self.gridLayout_2.addWidget(self.button_mark_start, 1, 9, 1, 1)
        self.btnSkipRight = QtWidgets.QToolButton(self.frame_media_control)
        self.btnSkipRight.setObjectName("btnSkipRight")
        self.gridLayout_2.addWidget(self.btnSkipRight, 1, 20, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 11, 1, 1)
        self.gridLayout.addWidget(self.frame_media_control, 0, 0, 1, 1)

        self.retranslateUi(RootWidget)
        QtCore.QMetaObject.connectSlotsByName(RootWidget)

    def retranslateUi(self, RootWidget):
        _translate = QtCore.QCoreApplication.translate
        RootWidget.setWindowTitle(_translate("RootWidget", "Form"))
        self.btnSkipLeft.setToolTip(_translate("RootWidget", "Skip Frames Left"))
        self.btnSkipLeft.setText(_translate("RootWidget", "<-"))
        self.btnSkipLeft.setShortcut(_translate("RootWidget", "Ctrl+Left"))
        self.toolButton_SpeedBurstEnabled.setStatusTip(_translate("RootWidget", "Trigger speedburst with the hotkey"))
        self.toolButton_SpeedBurstEnabled.setWhatsThis(_translate("RootWidget", "Trigger speedburst with the hotkey"))
        self.toolButton_SpeedBurstEnabled.setText(_translate("RootWidget", "SpeedBurst"))
        self.btnLeft.setToolTip(_translate("RootWidget", "Step Frames Left"))
        self.btnLeft.setText(_translate("RootWidget", "<"))
        self.btnLeft.setShortcut(_translate("RootWidget", "Left"))
        self.btnRight.setToolTip(_translate("RootWidget", "Step Frames Right"))
        self.btnRight.setText(_translate("RootWidget", ">"))
        self.btnRight.setShortcut(_translate("RootWidget", "Right"))
        self.button_play_pause.setText(_translate("RootWidget", "Play/Pause"))
        self.button_speed_up.setText(_translate("RootWidget", "Speed Up"))
        self.button_speed_up.setShortcut(_translate("RootWidget", "Ctrl+="))
        self.btnJumpToPrevious.setToolTip(_translate("RootWidget", "Jump to Previous"))
        self.btnJumpToPrevious.setStatusTip(_translate("RootWidget", "Jump to Previous"))
        self.btnJumpToPrevious.setText(_translate("RootWidget", "Jump to Prev."))
        self.btnJumpToUnused.setText(_translate("RootWidget", "..."))
        self.comboActiveJumpTargetSeries.setStatusTip(_translate("RootWidget", "The active series that the jump buttons operate on"))
        self.comboActiveJumpTargetSeries.setWhatsThis(_translate("RootWidget", "The active series that the jump buttons operate on"))
        self.comboActiveJumpTargetSeries.setPlaceholderText(_translate("RootWidget", "<No Target>"))
        self.btnJumpToNext.setToolTip(_translate("RootWidget", "Jump to Next"))
        self.btnJumpToNext.setStatusTip(_translate("RootWidget", "Jump to Next"))
        self.btnJumpToNext.setText(_translate("RootWidget", "Jump to Next"))
        self.button_slow_down.setText(_translate("RootWidget", "Slow Down"))
        self.button_slow_down.setShortcut(_translate("RootWidget", "Ctrl+S"))
        self.btnHelp.setText(_translate("RootWidget", "Help"))
        self.button_reverse.setText(_translate("RootWidget", "Reverse"))
        self.button_full_screen.setToolTip(_translate("RootWidget", "Set the video to full screen"))
        self.button_full_screen.setText(_translate("RootWidget", "Full Screen"))
        self.button_mark_end.setToolTip(_translate("RootWidget", "Mark the end of the entry"))
        self.button_mark_end.setText(_translate("RootWidget", "Mark End"))
        self.button_mark_start.setToolTip(_translate("RootWidget", "Mark the start of the entry"))
        self.button_mark_start.setText(_translate("RootWidget", "Mark Start"))
        self.btnSkipRight.setToolTip(_translate("RootWidget", "Skip Frames Right"))
        self.btnSkipRight.setText(_translate("RootWidget", "->"))
        self.btnSkipRight.setShortcut(_translate("RootWidget", "Ctrl+Right"))
from pyphocorehelpers.gui.Qt.HighlightedJumpSlider import HighlightedJumpSlider
from pyphocorehelpers.gui.Qt.ToggleButton import ToggleButton
from pyphoplacecellanalysis.Resources import ActionIcons
