# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlacefieldVisualSelectionWidgetBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rootForm(object):
    def setupUi(self, rootForm):
        rootForm.setObjectName("rootForm")
        rootForm.resize(1200, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(rootForm.sizePolicy().hasHeightForWidth())
        rootForm.setSizePolicy(sizePolicy)
        rootForm.setMinimumSize(QtCore.QSize(50, 0))
        rootForm.setBaseSize(QtCore.QSize(1200, 200))
        rootForm.setStyleSheet("background-color: rgb(71, 58, 46);\n"
"border-color: rgb(207, 207, 207);\n"
"background-color: rgba(71, 65, 60, 180);\n"
"color: rgb(244, 244, 244);\n"
"border-color: rgb(0, 0, 0);")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(rootForm)
        self.horizontalLayout_2.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.placefieldControlsGroupbox = QtWidgets.QGroupBox(rootForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placefieldControlsGroupbox.sizePolicy().hasHeightForWidth())
        self.placefieldControlsGroupbox.setSizePolicy(sizePolicy)
        self.placefieldControlsGroupbox.setObjectName("placefieldControlsGroupbox")
        self.outerLayout = QtWidgets.QVBoxLayout(self.placefieldControlsGroupbox)
        self.outerLayout.setContentsMargins(0, 0, 0, 0)
        self.outerLayout.setSpacing(0)
        self.outerLayout.setObjectName("outerLayout")
        self.scroll_area = QtWidgets.QScrollArea(self.placefieldControlsGroupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area.sizePolicy().hasHeightForWidth())
        self.scroll_area.setSizePolicy(sizePolicy)
        self.scroll_area.setBaseSize(QtCore.QSize(0, 150))
        self.scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_area.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.placefieldControlsContainer = QtWidgets.QWidget()
        self.placefieldControlsContainer.setGeometry(QtCore.QRect(0, 0, 1192, 69))
        self.placefieldControlsContainer.setBaseSize(QtCore.QSize(1200, 200))
        self.placefieldControlsContainer.setObjectName("placefieldControlsContainer")
        self.scroll_area.setWidget(self.placefieldControlsContainer)
        self.outerLayout.addWidget(self.scroll_area)
        self.horizontalLayout_2.addWidget(self.placefieldControlsGroupbox)

        self.retranslateUi(rootForm)
        QtCore.QMetaObject.connectSlotsByName(rootForm)

    def retranslateUi(self, rootForm):
        _translate = QtCore.QCoreApplication.translate
        rootForm.setWindowTitle(_translate("rootForm", "Placefield Controls"))
        self.placefieldControlsGroupbox.setTitle(_translate("rootForm", "Placefield Controls"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rootForm = QtWidgets.QWidget()
    ui = Ui_rootForm()
    ui.setupUi(rootForm)
    rootForm.show()
    sys.exit(app.exec_())
