# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\pyPhoPlaceCellAnalysis\src\pyphoplacecellanalysis\GUI\Qt\PlacefieldVisualSelectionControlsBar\PlacefieldVisualSelectionControlsBarWidgetBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rootForm(object):
    def setupUi(self, rootForm):
        rootForm.setObjectName("rootForm")
        rootForm.resize(1370, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(rootForm.sizePolicy().hasHeightForWidth())
        rootForm.setSizePolicy(sizePolicy)
        rootForm.setMinimumSize(QtCore.QSize(50, 0))
        rootForm.setMaximumSize(QtCore.QSize(16777215, 220))
        rootForm.setBaseSize(QtCore.QSize(1200, 200))
        rootForm.setStyleSheet("background-color: rgb(71, 58, 46);\n"
"border-color: rgb(207, 207, 207);\n"
"background-color: rgba(71, 65, 60, 180);\n"
"color: rgb(244, 244, 244);\n"
"border-color: rgb(0, 0, 0);")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(rootForm)
        self.horizontalLayout_2.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.placefieldControlsGroupbox = QtWidgets.QGroupBox(rootForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placefieldControlsGroupbox.sizePolicy().hasHeightForWidth())
        self.placefieldControlsGroupbox.setSizePolicy(sizePolicy)
        self.placefieldControlsGroupbox.setObjectName("placefieldControlsGroupbox")
        self.outerLayout = QtWidgets.QVBoxLayout(self.placefieldControlsGroupbox)
        self.outerLayout.setContentsMargins(0, 0, 0, 0)
        self.outerLayout.setSpacing(0)
        self.outerLayout.setObjectName("outerLayout")
        self.batchControlPanel = QtWidgets.QWidget(self.placefieldControlsGroupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchControlPanel.sizePolicy().hasHeightForWidth())
        self.batchControlPanel.setSizePolicy(sizePolicy)
        self.batchControlPanel.setMaximumSize(QtCore.QSize(16777215, 60))
        self.batchControlPanel.setBaseSize(QtCore.QSize(0, 30))
        self.batchControlPanel.setObjectName("batchControlPanel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.batchControlPanel)
        self.horizontalLayout.setContentsMargins(4, 2, 4, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.batchControlPanel)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setContentsMargins(2, 0, 2, 2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnShowAll_Pfs = QtWidgets.QPushButton(self.groupBox_2)
        self.btnShowAll_Pfs.setObjectName("btnShowAll_Pfs")
        self.buttonGroup = QtWidgets.QButtonGroup(rootForm)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.btnShowAll_Pfs)
        self.horizontalLayout_4.addWidget(self.btnShowAll_Pfs)
        self.btnShowAll_Spikes = QtWidgets.QPushButton(self.groupBox_2)
        self.btnShowAll_Spikes.setObjectName("btnShowAll_Spikes")
        self.buttonGroup.addButton(self.btnShowAll_Spikes)
        self.horizontalLayout_4.addWidget(self.btnShowAll_Spikes)
        self.btnShowAll_Both = QtWidgets.QPushButton(self.groupBox_2)
        self.btnShowAll_Both.setObjectName("btnShowAll_Both")
        self.buttonGroup.addButton(self.btnShowAll_Both)
        self.horizontalLayout_4.addWidget(self.btnShowAll_Both)
        self.horizontalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.batchControlPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnHideAll_Pfs = QtWidgets.QPushButton(self.groupBox)
        self.btnHideAll_Pfs.setMinimumSize(QtCore.QSize(0, 20))
        self.btnHideAll_Pfs.setBaseSize(QtCore.QSize(0, 24))
        self.btnHideAll_Pfs.setObjectName("btnHideAll_Pfs")
        self.horizontalLayout_3.addWidget(self.btnHideAll_Pfs)
        self.btnHideAll_Spikes = QtWidgets.QPushButton(self.groupBox)
        self.btnHideAll_Spikes.setObjectName("btnHideAll_Spikes")
        self.horizontalLayout_3.addWidget(self.btnHideAll_Spikes)
        self.btnHideAll_Both = QtWidgets.QPushButton(self.groupBox)
        self.btnHideAll_Both.setObjectName("btnHideAll_Both")
        self.horizontalLayout_3.addWidget(self.btnHideAll_Both)
        self.horizontalLayout.addWidget(self.groupBox)
        self.line_2 = QtWidgets.QFrame(self.batchControlPanel)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.grpExtraPlots = QtWidgets.QGroupBox(self.batchControlPanel)
        self.grpExtraPlots.setStyleSheet("QPushButton {\n"
"    /*background-color: green;*/\n"
"    color: rgb(244, 244, 244);\n"
"    /*border: 2px green;*/\n"
"    /*border-radius: 22px;*/\n"
"    /*border-style: outset;*/\n"
"    /*border-style: inset;*/\n"
"}\n"
"QPushButton:disabled {\n"
"    color: gray;\n"
"    background-color: gray;\n"
"    border: 1px black;\n"
"    border-style: outset;                \n"
"}\n"
"QPushButton:checked{\n"
"    color: rgb(255, 170, 0); \n"
"    /*font:  12px; */  \n"
"    font: bold;\n"
"    /*background-color: red;*/\n"
"    border: 1px white;\n"
"    border-style: outset;\n"
"}\n"
"QToolButton:!checked{\n"
"    /*color: black; */\n"
"    /*background-color: green;*/\n"
"    /*border: 1px black;*/\n"
"    /*border-style: outset;*/\n"
"    /*border: 1px black;*/\n"
"    /*border-style: dashed;*/\n"
"}")
        self.grpExtraPlots.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.grpExtraPlots.setObjectName("grpExtraPlots")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.grpExtraPlots)
        self.horizontalLayout_5.setContentsMargins(2, 0, 2, 2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnToggleOccupancy = QtWidgets.QPushButton(self.grpExtraPlots)
        self.btnToggleOccupancy.setCheckable(True)
        self.btnToggleOccupancy.setObjectName("btnToggleOccupancy")
        self.horizontalLayout_5.addWidget(self.btnToggleOccupancy)
        self.btnNonPlacefieldSpikes = QtWidgets.QPushButton(self.grpExtraPlots)
        self.btnNonPlacefieldSpikes.setCheckable(True)
        self.btnNonPlacefieldSpikes.setChecked(True)
        self.btnNonPlacefieldSpikes.setObjectName("btnNonPlacefieldSpikes")
        self.horizontalLayout_5.addWidget(self.btnNonPlacefieldSpikes)
        self.btnDebugTest = QtWidgets.QPushButton(self.grpExtraPlots)
        self.btnDebugTest.setCheckable(True)
        self.btnDebugTest.setObjectName("btnDebugTest")
        self.horizontalLayout_5.addWidget(self.btnDebugTest)
        self.horizontalLayout.addWidget(self.grpExtraPlots)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(self.batchControlPanel)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.toolButton_2 = QtWidgets.QToolButton(self.batchControlPanel)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.toolButton = QtWidgets.QToolButton(self.batchControlPanel)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.btnRefresh = QtWidgets.QPushButton(self.batchControlPanel)
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout.addWidget(self.btnRefresh)
        self.outerLayout.addWidget(self.batchControlPanel)
        self.scroll_area = QtWidgets.QScrollArea(self.placefieldControlsGroupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area.sizePolicy().hasHeightForWidth())
        self.scroll_area.setSizePolicy(sizePolicy)
        self.scroll_area.setBaseSize(QtCore.QSize(0, 150))
        self.scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_area.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.placefieldControlsContainer = QtWidgets.QWidget()
        self.placefieldControlsContainer.setGeometry(QtCore.QRect(0, 0, 1362, 130))
        self.placefieldControlsContainer.setBaseSize(QtCore.QSize(1200, 200))
        self.placefieldControlsContainer.setObjectName("placefieldControlsContainer")
        self.scroll_area.setWidget(self.placefieldControlsContainer)
        self.outerLayout.addWidget(self.scroll_area)
        self.outerLayout.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.placefieldControlsGroupbox)

        self.retranslateUi(rootForm)
        QtCore.QMetaObject.connectSlotsByName(rootForm)

    def retranslateUi(self, rootForm):
        _translate = QtCore.QCoreApplication.translate
        rootForm.setWindowTitle(_translate("rootForm", "Placefield Controls"))
        self.placefieldControlsGroupbox.setTitle(_translate("rootForm", "Placefield Controls"))
        self.groupBox_2.setTitle(_translate("rootForm", "Show All"))
        self.btnShowAll_Pfs.setToolTip(_translate("rootForm", "Show All Placefields"))
        self.btnShowAll_Pfs.setAccessibleDescription(_translate("rootForm", "Show All Placefields"))
        self.btnShowAll_Pfs.setText(_translate("rootForm", "Show All Placefields"))
        self.btnShowAll_Spikes.setToolTip(_translate("rootForm", "Show All Spikes"))
        self.btnShowAll_Spikes.setAccessibleDescription(_translate("rootForm", "Show All Spikes"))
        self.btnShowAll_Spikes.setText(_translate("rootForm", "Show All Spikes"))
        self.btnShowAll_Both.setToolTip(_translate("rootForm", "Show All Both"))
        self.btnShowAll_Both.setAccessibleDescription(_translate("rootForm", "Show All Both"))
        self.btnShowAll_Both.setText(_translate("rootForm", "Show All Both"))
        self.groupBox.setTitle(_translate("rootForm", "Hide All"))
        self.btnHideAll_Pfs.setToolTip(_translate("rootForm", "Hide All Placefields"))
        self.btnHideAll_Pfs.setAccessibleDescription(_translate("rootForm", "Hide All Placefields"))
        self.btnHideAll_Pfs.setText(_translate("rootForm", "Hide All Placefields"))
        self.btnHideAll_Spikes.setToolTip(_translate("rootForm", "Hide All Spikes"))
        self.btnHideAll_Spikes.setAccessibleDescription(_translate("rootForm", "Hide All Spikes"))
        self.btnHideAll_Spikes.setText(_translate("rootForm", "Hide All Spikes"))
        self.btnHideAll_Both.setToolTip(_translate("rootForm", "Hide All Both"))
        self.btnHideAll_Both.setAccessibleDescription(_translate("rootForm", "Hide All Both"))
        self.btnHideAll_Both.setText(_translate("rootForm", "Hide All Both"))
        self.grpExtraPlots.setTitle(_translate("rootForm", "Extra Plots"))
        self.btnToggleOccupancy.setText(_translate("rootForm", "Occupancy"))
        self.btnNonPlacefieldSpikes.setText(_translate("rootForm", "Non-Placefield Spikes"))
        self.btnDebugTest.setText(_translate("rootForm", "PushButton"))
        self.toolButton_2.setText(_translate("rootForm", "..."))
        self.toolButton.setText(_translate("rootForm", "..."))
        self.btnRefresh.setToolTip(_translate("rootForm", "Refresh"))
        self.btnRefresh.setAccessibleDescription(_translate("rootForm", "Refresh"))
        self.btnRefresh.setText(_translate("rootForm", "Refresh"))
