# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\pyPhoPlaceCellAnalysis\src\pyphoplacecellanalysis\GUI\Qt\FigureFormatConfigControls\FigureFormatConfigControls.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(431, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tupleCtrl_0 = SingleGroupOptionalMembersCtrl(Form)
        self.tupleCtrl_0.setObjectName("tupleCtrl_0")
        self.verticalLayout.addWidget(self.tupleCtrl_0)
        self.tupleCtrl_1 = SingleGroupOptionalMembersCtrl(Form)
        self.tupleCtrl_1.setObjectName("tupleCtrl_1")
        self.verticalLayout.addWidget(self.tupleCtrl_1)
        self.tupleCtrl_2 = SingleGroupOptionalMembersCtrl(Form)
        self.tupleCtrl_2.setObjectName("tupleCtrl_2")
        self.verticalLayout.addWidget(self.tupleCtrl_2)
        self.chkEnableSpikeOverlay = QtWidgets.QCheckBox(Form)
        self.chkEnableSpikeOverlay.setObjectName("chkEnableSpikeOverlay")
        self.verticalLayout.addWidget(self.chkEnableSpikeOverlay)
        self.chkDebugPrint = QtWidgets.QCheckBox(Form)
        self.chkDebugPrint.setObjectName("chkDebugPrint")
        self.verticalLayout.addWidget(self.chkDebugPrint)
        self.chkEnableSavingToDisk = QtWidgets.QCheckBox(Form)
        self.chkEnableSavingToDisk.setChecked(True)
        self.chkEnableSavingToDisk.setObjectName("chkEnableSavingToDisk")
        self.verticalLayout.addWidget(self.chkEnableSavingToDisk)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        self.chkEnableSpikeOverlay.toggled['bool'].connect(Form.on_update_values) # type: ignore
        self.chkDebugPrint.toggled['bool'].connect(Form.on_update_values) # type: ignore
        self.chkEnableSavingToDisk.toggled['bool'].connect(Form.on_update_values) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.chkEnableSpikeOverlay.setText(_translate("Form", "enable_spike_overlay"))
        self.chkDebugPrint.setText(_translate("Form", "debug_print"))
        self.chkEnableSavingToDisk.setText(_translate("Form", "enable_saving_to_disk"))
        self.pushButton.setText(_translate("Form", "Open Out folder in System File Manager"))
from pyphoplacecellanalysis.GUI.Qt.FigureFormatConfigControls.SingleGroupOptionalMembersCtrl import SingleGroupOptionalMembersCtrl
